<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/11/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * Price estimates for products
 */
class PriceEsitmate implements JsonSerializable {
    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     * @required
     * @maps product_id
     * @var string $productId public property
     */
    public $productId;

    /**
     * ISO 4217 currency code.
     * @required
     * @maps currency_code
     * @var string $currencyCode public property
     */
    public $currencyCode;

    /**
     * Display name of product.
     * @required
     * @maps display_name
     * @var string $displayName public property
     */
    public $displayName;

    /**
     * Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or "Metered" for TAXI.
     * @required
     * @var string $estimate public property
     */
    public $estimate;

    /**
     * Lower bound of the estimated price.
     * @required
     * @maps low_estimate
     * @var int $lowEstimate public property
     */
    public $lowEstimate;

    /**
     * Upper bound of the estimated price.
     * @required
     * @maps high_estimate
     * @var int $highEstimate public property
     */
    public $highEstimate;

    /**
     * Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
     * @required
     * @maps surge_multiplier
     * @var double $surgeMultiplier public property
     */
    public $surgeMultiplier;

    /**
     * Expected activity duration (in seconds). Always show duration in minutes.
     * @required
     * @var int $duration public property
     */
    public $duration;

    /**
     * Expected activity distance (in miles).
     * @required
     * @var double $distance public property
     */
    public $distance;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   string            $productId          Initialization value for the property $this->productId       
	 * @param   string            $currencyCode       Initialization value for the property $this->currencyCode    
	 * @param   string            $displayName        Initialization value for the property $this->displayName     
	 * @param   string            $estimate           Initialization value for the property $this->estimate        
	 * @param   int               $lowEstimate        Initialization value for the property $this->lowEstimate     
	 * @param   int               $highEstimate       Initialization value for the property $this->highEstimate    
	 * @param   double            $surgeMultiplier    Initialization value for the property $this->surgeMultiplier 
	 * @param   int               $duration           Initialization value for the property $this->duration        
	 * @param   double            $distance           Initialization value for the property $this->distance        
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->productId        = func_get_arg(0);
            $this->currencyCode     = func_get_arg(1);
            $this->displayName      = func_get_arg(2);
            $this->estimate         = func_get_arg(3);
            $this->lowEstimate      = func_get_arg(4);
            $this->highEstimate     = func_get_arg(5);
            $this->surgeMultiplier  = func_get_arg(6);
            $this->duration         = func_get_arg(7);
            $this->distance         = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['product_id']       = $this->productId;
        $json['currency_code']    = $this->currencyCode;
        $json['display_name']     = $this->displayName;
        $json['estimate']         = $this->estimate;
        $json['low_estimate']     = $this->lowEstimate;
        $json['high_estimate']    = $this->highEstimate;
        $json['surge_multiplier'] = $this->surgeMultiplier;
        $json['duration']         = $this->duration;
        $json['distance']         = $this->distance;

        return $json;
    }
}