<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Request extends ErrorBase implements JsonSerializable {
    /**
     * The unique ID of the Request.
     * @required
     * @maps request_id
     * @var string $requestId public property
     */
    public $requestId;

    /**
     * The status of the Request indicating state.
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * The object that contains vehicle details.
     * @required
     * @var array $vehicle public property
     */
    public $vehicle;

    /**
     * The object that contains driver details.
     * @required
     * @var array $driver public property
     */
    public $driver;

    /**
     * The object that contains the location information of the vehicle and driver
     * @required
     * @var array $location public property
     */
    public $location;

    /**
     * The estimated time of vehicle arrival in minutes.
     * @required
     * @var int $eta public property
     */
    public $eta;

    /**
     * The surge pricing multiplier used to calculate the increased price of a Request. A multiplier of 1.0 means surge pricing is not in effect.
     * @required
     * @maps surge_multiplier
     * @var double $surgeMultiplier public property
     */
    public $surgeMultiplier;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   string            $requestId          Initialization value for the property $this->requestId       
	 * @param   string            $status             Initialization value for the property $this->status          
	 * @param   array             $vehicle            Initialization value for the property $this->vehicle         
	 * @param   array             $driver             Initialization value for the property $this->driver          
	 * @param   array             $location           Initialization value for the property $this->location        
	 * @param   int               $eta                Initialization value for the property $this->eta             
	 * @param   double            $surgeMultiplier    Initialization value for the property $this->surgeMultiplier 
     */
    public function __construct()
    {
        if(7 == func_num_args())
        {
            $this->requestId        = func_get_arg(0);
            $this->status           = func_get_arg(1);
            $this->vehicle          = func_get_arg(2);
            $this->driver           = func_get_arg(3);
            $this->location         = func_get_arg(4);
            $this->eta              = func_get_arg(5);
            $this->surgeMultiplier  = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['request_id']       = $this->requestId;
        $json['status']           = $this->status;
        $json['vehicle']          = $this->vehicle;
        $json['driver']           = $this->driver;
        $json['location']         = $this->location;
        $json['eta']              = $this->eta;
        $json['surge_multiplier'] = $this->surgeMultiplier;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}