<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * The record user activity in history
 */
class UserActivity implements JsonSerializable {
    /**
     * Position in pagination.
     * @required
     * @var int $offset public property
     */
    public $offset;

    /**
     * Number of items to retrieve (100 max).
     * @required
     * @var int $limit public property
     */
    public $limit;

    /**
     * Total number of items available.
     * @required
     * @var int $count public property
     */
    public $count;

    /**
     * Information including the pickup location, dropoff location, request start time, request end time, and distance of requests (in miles), as well as the product type that was requested.
     * @required
     * @var array $history public property
     */
    public $history;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   int               $offset    Initialization value for the property $this->offset 
	 * @param   int               $limit     Initialization value for the property $this->limit  
	 * @param   int               $count     Initialization value for the property $this->count  
	 * @param   array             $history   Initialization value for the property $this->history
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->offset  = func_get_arg(0);
            $this->limit   = func_get_arg(1);
            $this->count   = func_get_arg(2);
            $this->history = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['offset']  = $this->offset;
        $json['limit']   = $this->limit;
        $json['count']   = $this->count;
        $json['history'] = $this->history;

        return $json;
    }
}