<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/09/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * The object that contains vehicle details.
 */
class Vehicle implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $make public property
     */
    public $make;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $model public property
     */
    public $model;

    /**
     * @todo Write general description for this property
     * @required
     * @maps license_plate
     * @var string $licensePlate public property
     */
    public $licensePlate;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   string            $make            Initialization value for the property $this->make         
	 * @param   string            $model           Initialization value for the property $this->model        
	 * @param   string            $licensePlate    Initialization value for the property $this->licensePlate 
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->make          = func_get_arg(0);
            $this->model         = func_get_arg(1);
            $this->licensePlate  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['make']          = $this->make;
        $json['model']         = $this->model;
        $json['license_plate'] = $this->licensePlate;

        return $json;
    }
}