<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 08/12/2016
 */

namespace UberAPILib;

use UberAPILib\Controllers;

/**
 * UberAPILib client class
 */
class UberAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($oAuthAccessToken = NULL)
    {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
 
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getClient()
    {
        return Controllers\APIController::getInstance();
    }
}