<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/11/2016
 */

namespace UberAPILib;

use UberAPILib\Controllers;

/**
 * UberAPILib client class
 */
class UberAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($oAuthAccessToken = NULL)
    {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
 
	/**
	 * Singleton access to API controller
	 * @return APIController The *Singleton* instance
	 */
	public function getAPI()
	{
		return Controllers\APIController::getInstance();
	}
}